trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: 'TF_VAR_client_id'
    value: '$(servicePrincipalId)'
  - name: 'TF_VAR_client_secret'
    value: '$(servicePrincipalKey)'
  - name: 'TF_VAR_subscription_id'
    value: '$(subscriptionId)'
  - name: 'TF_VAR_tenant_id'
    value: '$(tenantId)'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Terraform Init'

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      commandOptions: '-out=tfplan'
    displayName: 'Terraform Plan'

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      commandOptions: '-auto-approve tfplan'
    displayName: 'Terraform Apply'
