trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: TerraformVariables

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'azure-spn'
      backendAzureRmResourceGroupName: '$(resourceGroupName)'
      backendAzureRmStorageAccountName: '$(storageAccountName)'
      backendAzureRmContainerName: '$(containerName)'
      backendAzureRmKey: '$(tfstateFileName)'

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'azure-spn'
      commandOptions: '-out=tfplan'

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'azure-spn'
      commandOptions: '-auto-approve tfplan'
