trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure-spn'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      commandOptions: '-migrate-state'
      backendServiceArm: 'azure-spn'
      backendAzureRmResourceGroupName: 'Terraform-Backend'
      backendAzureRmStorageAccountName: 'terraformbackendshubh'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      commandOptions: '-out=tfplan'
      environmentServiceNameAzureRM: 'azure-spn'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto-approve tfplan'
      environmentServiceNameAzureRM: 'azure-spn'
