trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: 'TF_VAR_client_id'
    value: '$(servicePrincipalId)'
  - name: 'TF_VAR_client_secret'
    value: '$(servicePrincipalKey)'
  - name: 'TF_VAR_subscription_id'
    value: '$(subscriptionId)'
  - name: 'TF_VAR_tenant_id'
    value: '$(tenantId)'

stages:
- stage: Terraform
  jobs:
  - job: Terraform
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - script: |
        terraform init
      displayName: 'Terraform Init'

    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
